title: SPARQL API comparison
author: Arcangelo Massari
copyright: "2026"

exclude_patterns:
  - _build

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/arcangelo7/sparql-api-comparison
  branch: master
  path_to_book: docs

html:
  use_issues_button: true
  use_repository_button: true
  baseurl: https://arcangelo7.github.io/sparql-api-comparison
